# Generated by Django 2.2 on 2020-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description bla bla bla bla bla bla bla bla bla bla'),
            preserve_default=False,
        ),
    ]
